### ISSUE TITLE
HyperParameter vs AlgorithmParameter

### ISSUE THREAD

**Issue by mommi84** [AKSW/mexproject#43]
Evaluate the possibility of introducing a `mexalgo:HyperParameter` class to distinguish between prior parameters (e.g., C and &gamma;) and parameters of the model that is being learned.

Alternative resolutions:
* Keep using `mexalgo:AlgorithmParameter`.

**Comment by dnes85** [comment]
Personally I would not vote against that. Just one consideration: ```Hyper Parameters``` and ```Algorithm Parameters```, technically, are the same and in MEX we (so far) do not map ```model``` parameters (the ones which are optimized during the training phase). Im my opinion (also), the *alternative solution* you've mentioned would not work (not technically, but philosophically) and we have never planned to use ```mexalgo:AlgorithmParameter``` as entity to represent ```model parameters```.

**Comment by dnes85** [comment]
Back to the issue, I do not see too much advantage of representing ```model parameters``` (since this is a information that can be derived and users would not do it manually). However, I do understand that it's important if you want to integrate the schema into a Repository, such as OpenML. Therefore, I vote to create a separated class ```mexalgo:HyperParameter``` as you've suggested. But, I have one question here: Shouldn't it be related to the ```mexcore:Execution``` and the ```mexcore:Model```? Once this is information is learned during the training phase, it just exists with the execution/run.

**Comment by DiegoMoussallem** [comment]
For the ML perspective `Hyper Parameter` and `Algorithm Parameter` are the same thing. But to integrate MEX into OpenML, I vote to rename the class and to create a new one as Esteves mentioned. About Esteves's question, I think `mexalgo:ModelParameter` would be the better apropriate way as `mexcore:ModelParameter` directly linked to 'mexcore:Model` and `mexalgo:HyperParameter`.
