### ISSUE TITLE
OpenML Workshop discussion thread

### ISSUE THREAD

**Issue by mommi84** [AKSW/mexproject#46]
**Facts**
From the workshop:
> Team Linked Open Data - Link OpenML data, code, experiments to the semantic web
_Tommaso Soru - Agnieszka Lawrynowicz - Pance Panov_
Ideas:
- Complete an initial specification of ML-Schema to share ML experiments as linked open data (LOD)
- Discuss links and compliance to existing efforts in this area (e.g. ISA tools)
- Provide proof of concept where OpenML experiments are exported as LOD

**Questions**
1. None of the three things they listed is practical... Isn't the workshop supposed to feature a hackathon?
2. Are we (as MEX) supposed to implement a MEX2ML-Schema translator back and forth? I'd rather use ML-Schema as a reference point and avoid translating MEX directly to OpenML and others.
3. If so, can you please point me to the right part of the project so I can reuse existing code?
4. I still haven't understood what it is meant in #39 
5. Please add your own views, if any.

Cheers!

**Comment by dnes85** [comment]
Hi all,

1 - yes, as far as I understood it's going to be a hackathon.
2 - "ML-Schema" is suppose to be an upper level reference to everybody use it, instead of MEX, OntoDM, Exposé and so on. You could follow this idea and focus more on ML-Schema, it's up to you I think. Just would be nice if you link things back to MEX (in case you find a situation that MEX doesn't cover (and it should, following its principles).
3 - You don't. Let's have a meeting in person afterwards, so we (together) can update MEX and release it based on discussed topics.
4 - The correlation is kind of premature. We should link MEX with ML-Schema instead of linking with OpenML (which is much more a tool than a simple schema)
5 - You should consider https://worksheets.codalab.org/ and http://mlcomp.org/ besides ISA

All the best

**Comment by DiegoMoussallem** [comment]
Hi Folks, 

1 - yes, it will be a hackathon. 
2 - I think that the main ideia was to map directly MEX2OpenML. When, you find some particular situation not covered by MEX, you should use ML-Schema. 
3 - I can't speak anything relevant about it. 
4 - Now, I got confused. I though that we'd link MEX2ML-Schema after the MEX2OpenML exporter.
5 -  Nothing. Have a nice workshop.
